<?php

global $unocoinOptions;

// do not edit this file
// all values are set via config settings or upon use


$unocoinOptions['secret'] = '';

$unocoinOptions['notificationEmail'] = '';

$unocoinOptions['notificationURL'] = '';

$unocoinOptions['redirectURL'] = '';

$unocoinOptions['currency'] = '';

$unocoinOptions['physical'] = 'true';

$unocoinOptions['fullNotifications'] = 'true';

$unocoinOptions['transactionSpeed'] = 'low'; 

?>
